#!/bin/bash
# build_picolibc.sh - Clone and build picolibc for M65832
#
# This script:
# 1. Clones picolibc to an adjacent folder if not present
# 2. Checks out a specific release tag for reproducibility
# 3. Builds picolibc with the M65832 cross-compiler
# 4. Installs to a local prefix for use by the toolchain

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
STDLIB_DIR="$(dirname "$SCRIPT_DIR")"
PROJECTS_DIR="$(dirname "$(dirname "$STDLIB_DIR")")"

# Use our fork with M65832 support
PICOLIBC_REPO="https://github.com/benjcooley/picolibc-m65832.git"
PICOLIBC_BRANCH="main"  # We'll tag releases later

# Directories
PICOLIBC_SRC="$PROJECTS_DIR/picolibc-m65832"
PICOLIBC_BUILD="$PROJECTS_DIR/picolibc-build-m65832"
INSTALL_PREFIX="$PROJECTS_DIR/m65832-sysroot"
LLVM_BUILD="$PROJECTS_DIR/llvm-m65832/build"

# Tools
CLANG="$LLVM_BUILD/bin/clang"
LLVM_AR="$LLVM_BUILD/bin/llvm-ar"
LLVM_RANLIB="$LLVM_BUILD/bin/llvm-ranlib"

echo "=========================================="
echo "M65832 Picolibc Build Script"
echo "=========================================="
echo ""
echo "Repo:      $PICOLIBC_REPO"
echo "Source:    $PICOLIBC_SRC"
echo "Build:     $PICOLIBC_BUILD"
echo "Install:   $INSTALL_PREFIX"
echo "LLVM:      $LLVM_BUILD"
echo ""

# Check for LLVM tools
if [ ! -x "$CLANG" ]; then
    echo "ERROR: clang not found at $CLANG"
    echo "Please build LLVM first: cd llvm-m65832/build && cmake --build . --target clang"
    exit 1
fi

# Check for meson
if ! command -v meson &> /dev/null; then
    echo "ERROR: meson not found. Install with: pip install meson"
    exit 1
fi

# Step 1: Clone picolibc-m65832 fork if needed
if [ ! -d "$PICOLIBC_SRC" ]; then
    echo ">>> Cloning picolibc-m65832 fork..."
    git clone "$PICOLIBC_REPO" "$PICOLIBC_SRC"
    echo ">>> picolibc-m65832 cloned successfully"
else
    echo ">>> picolibc-m65832 source exists at $PICOLIBC_SRC"
    cd "$PICOLIBC_SRC"
    echo "    Branch: $(git branch --show-current)"
fi

# Step 2: Create clang wrapper and cross file
CROSS_FILE="$STDLIB_DIR/picolibc/cross-m65832.txt"
CLANG_WRAPPER="$STDLIB_DIR/picolibc/m65832-clang"

echo ">>> Generating clang wrapper..."
cat > "$CLANG_WRAPPER" << 'EOF'
#!/bin/bash
# Wrapper for clang that adds M65832 target flags
exec /Users/benjamincooley/projects/llvm-m65832/build/bin/clang \
    -target m65832-elf \
    -ffreestanding \
    "$@"
EOF
chmod +x "$CLANG_WRAPPER"

echo ">>> Generating cross-compilation file..."
cat > "$CROSS_FILE" << EOF
# Meson cross-compilation file for M65832
# Auto-generated by build_picolibc.sh

[constants]
stdlib_dir = '$STDLIB_DIR'

[binaries]
c = '$CLANG_WRAPPER'
ar = 'ar'
as = '$CLANG_WRAPPER'
ld = '$LLVM_BUILD/bin/ld.lld'
strip = 'strip'
ranlib = 'ranlib'
exe_wrapper = ['$STDLIB_DIR/picolibc/run-m65832.sh']

[built-in options]
# Note: -g disabled due to debug info crash in MCAssembler::layout() - bug to fix
# Note: -O2+ disabled due to analyzeBranch() crash in BranchFolder - bug to fix  
c_args = ['-O1']
c_link_args = ['-nostdlib']

[host_machine]
system = 'none'
cpu_family = 'm65832'
cpu = 'm65832'
endian = 'little'

[properties]
skip_sanity_check = true
EOF

# Step 3: Configure picolibc with meson
echo ""
echo ">>> Configuring picolibc for m65832-elf..."

# Remove old build if exists
if [ -d "$PICOLIBC_BUILD" ]; then
    echo "    Removing old build directory..."
    rm -rf "$PICOLIBC_BUILD"
fi

meson setup "$PICOLIBC_BUILD" "$PICOLIBC_SRC" \
    --cross-file "$CROSS_FILE" \
    --prefix="$INSTALL_PREFIX" \
    --buildtype=plain \
    -Ddebug=false \
    -Doptimization=1 \
    -Dmultilib=false \
    -Dtests=false \
    -Dspecsdir=none \
    -Dfreestanding=true

echo ">>> Configuration complete"

# Step 4: Build
echo ""
echo ">>> Building picolibc..."
meson compile -C "$PICOLIBC_BUILD"

# Step 5: Install
echo ""
echo ">>> Installing to $INSTALL_PREFIX..."
meson install -C "$PICOLIBC_BUILD"

# Step 6: Compile and install our M65832-specific files
echo ""
echo ">>> Installing M65832-specific files..."

M65832_LIB="$INSTALL_PREFIX/lib"
M65832_INC="$INSTALL_PREFIX/include"
mkdir -p "$M65832_LIB" "$M65832_INC"

# Compile syscalls
"$CLANG" -target m65832-elf -ffreestanding -O2 -g \
    -I"$M65832_INC" \
    -c "$STDLIB_DIR/picolibc/syscalls.c" -o "$M65832_LIB/syscalls.o"

# Compile crt0
"$CLANG" -target m65832-elf -ffreestanding -O2 -g \
    -I"$M65832_INC" \
    -c "$STDLIB_DIR/picolibc/crt0.c" -o "$M65832_LIB/crt0.o"

# Copy linker script
cp "$STDLIB_DIR/picolibc/m65832.ld" "$M65832_LIB/"

# Create libsys.a with syscalls
"$LLVM_AR" rcs "$M65832_LIB/libsys.a" "$M65832_LIB/syscalls.o"

echo ""
echo "=========================================="
echo "Build Complete!"
echo "=========================================="
echo ""
echo "Installed to: $INSTALL_PREFIX"
echo ""
echo "To use picolibc in your projects:"
echo ""
echo "  # Compile"
echo "  clang -target m65832-elf -ffreestanding \\"
echo "    -I$INSTALL_PREFIX/include \\"
echo "    -c myprogram.c -o myprogram.o"
echo ""
echo "  # Link"
echo "  ld.lld -T $M65832_LIB/m65832.ld \\"
echo "    $M65832_LIB/crt0.o myprogram.o \\"
echo "    -L$M65832_LIB -lc -lsys -lm \\"
echo "    -o myprogram.elf"
echo ""
